language: c

compiler:
- clang

os:
- linux
# - osx # currently builds too slowly ...

before_install:
- cd ..
- basedir=${PWD}
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- mkdir -p ~/.R
- export CC=clang
- export CXX=clang++
- echo "CC=clang" >  ~/.R/Makevars
- echo "CXX=clang++" >> ~/.R/Makevars
- source ~/.R/Makevars

install:
- wget https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
- unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
    -d $HOME/pandoc
- chmod +x $HOME/pandoc/pandoc
- export PATH=$PATH:$HOME/pandoc/
- pandoc --version
- ./travis-tool.sh bootstrap
- ./travis-tool.sh github_package jimhester/covr
- ./travis-tool.sh r_install BGLR
- ./travis-tool.sh r_binary_install caret
- ./travis-tool.sh r_binary_install cluster
- ./travis-tool.sh r_install DMwR
- ./travis-tool.sh r_binary_install e1071
- ./travis-tool.sh r_binary_install fastICA
- ./travis-tool.sh r_install fpc
- ./travis-tool.sh r_install grid
- ./travis-tool.sh r_binary_install glmnet
- ./travis-tool.sh r_binary_install igraph
- ./travis-tool.sh r_binary_install magic
- ./travis-tool.sh r_binary_install misc3d
- ./travis-tool.sh r_binary_install moments
- ./travis-tool.sh r_binary_install pixmap
- ./travis-tool.sh r_binary_install png
- ./travis-tool.sh r_binary_install psych
- ./travis-tool.sh r_binary_install randomForest
- ./travis-tool.sh r_binary_install rgl
- ./travis-tool.sh r_binary_install robust
- ./travis-tool.sh r_binary_install signal
- ./travis-tool.sh r_install visreg
- ./travis-tool.sh r_binary_install Rcpp
- ./travis-tool.sh r_binary_install knitr
- ./travis-tool.sh r_install rmarkdown
- cd ${basedir}

script:
- R CMD INSTALL ANTsR
# - R CMD check ANTsR
# - R CMD  check ANTsR_1.0.tar.gz --no-install --as-cran

after_success:
- Rscript -e 'devtools::install()'
- Rscript -e 'library(covr);coveralls()'

after_failure:
- ./travis-tool.sh dump_logs

notifications:
  email:
    recipients:
    - arman.eshaghi@gmail.com
    on_success: change
    on_failure: always

env:
  global:
  - R_BUILD_ARGS=" "
  - R_CHECK_ARGS=" --timings"
  - R_CHECK_TIME="TRUE"
  - R_CHECK_TESTS="TRUE"
  - _R_CHECK_TIMINGS_="0"
